experiment_name: svhn_detr_final_3500_750

dataset:
  name: ufldl-stanford/svhn
  config: full_numbers
  validation_fraction: 0.10
  max_train_samples: 3500
  max_val_samples: 750
model:
  name: facebook/detr-resnet-50
  num_labels: 10
training:
  epochs: 5
  batch_size: 4
  learning_rate: 0.0001
  weight_decay: 0.0001
seed: 42
